const val rootGroup = "ru.snapix"
const val rootVersion = "1.1"

const val kotlinVersion = "1.9.23"
const val shadowJarVersion = "7.1.2"
const val velocityVersion = "3.2.0-SNAPSHOT"
const val protocolizeVersion = "2.3.3"
const val dazzleConfVersion = "1.2.1"
const val redisVersion = "5.1.0"
const val hikariCPVersion = "5.1.0"
const val mariadb = "3.3.3"
const val coroutinesVersion = "1.7.3"
const val acfVersion = "0.5.1-SNAPSHOT"
