const val rootName = "SnapiLibrary"
const val rootGroup = "ru.snapix"
const val rootVersion = "1.4.1"
const val libraryPackage = "ru.snapix.library.libs"

const val kotlinVersion = "2.0.0"
const val kotlinSerializationVersion = "1.7.0"
const val shadowJarVersion = "7.1.2"
const val velocityVersion = "3.2.0-SNAPSHOT"
const val protocolizeVersion = "2.3.3"
const val dazzleConfVersion = "1.2.1"
const val kredsVersion = "0.9.1"
const val mariadbVersion = "3.4.0"
const val coroutinesVersion = "1.9.0-RC"
const val acfVersion = "0.5.1-SNAPSHOT"
const val exposedVersion = "0.51.1"
